No module named "Detectron2" Bug Fix
autodistill/autodistill-detic pull request #1
Opened 2023-06-08 23:02 UTC by artyaltanzaya

## Changes made

In `setup.py` added CustomInstall class `AutodistillDetic` for installing dependencies when building. Some minor typo error.  Install_detic() function is not removed or modified in the `detic_model.py`

## Tests

Ran in google colab with `pip install . ` and in conda environment in Mac with `pip install . ` and compared the result with `pip3 install autodistill-detic` in different conda environment. 

`pip3 install autodistill-detic` returns error such as "no module named supervision, autodistill, or detectron2"

With new modified setup.py using `pip install . `, the errors are fixed. 

Please test for further potential errors.

2023-06-09 20:13 UTC, capjamesg requested changes
This is an elegant implementation! Can you remove the installation commands and associated installation functions and calls from the https://github.com/autodistill/autodistill-detic/blob/main/autodistill_detic/detic_model.py file?

2023-06-12 17:21 UTC, artyaltanzaya commented
removed installation commands!

2023-06-14 10:23 UTC, artyaltanzaya commented
UPDATE: now install works but using the package returns further errors! Will take a look at it and fix it!

```
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 1
----> 1 base_model = DETIC(ontology=CaptionOntology({"airplane": "airplane"}))

     20 def setup_cfg(args):
---> 21     from centernet.config import add_centernet_config
     22     from detic.config import add_detic_config
     23     cfg = get_cfg()

ModuleNotFoundError: No module named 'centernet'`
```

2023-06-14 13:19 UTC, capjamesg commented
@artyaltanzaya Can you share the code you are running?

2023-06-14 15:21 UTC, artyaltanzaya commented
To reproduce the bug try running

`base_model = DETIC(
    ontology=CaptionOntology(
        {
            "person": "person",
        }
    )
) ` after installation 

FYI, I fixed it on the new commit and now able to run the model!

2023-06-14 17:02 UTC, merged